-- Core schema for RougaRoux MVP
create table if not exists profiles (id uuid primary key, role text default 'reader', display_name text, created_at timestamptz default now());
create table if not exists article_categories (id bigserial primary key, slug text unique, name text not null);
create table if not exists articles (id bigserial primary key,title text not null,subtitle text,slug text unique not null,excerpt text,body text,category text,tags text[],status text default 'draft',author_name text,author_type text default 'ai',hero_image_url text,seo_title text,seo_description text,source_summary text,confidence_score numeric(3,2),fact_check_status text default 'pending',sponsored_status boolean default false,advertiser_id bigint,published_at timestamptz,scheduled_for timestamptz,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists article_sources (id bigserial primary key, article_id bigint references articles(id) on delete cascade, source_url text not null, source_title text, reliability_score int, created_at timestamptz default now());
create table if not exists events (id bigserial primary key,title text not null,description text,event_date timestamptz,neighborhood text,category text,price_text text,family_friendly boolean default false,status text default 'pending');
create table if not exists event_submissions (id bigserial primary key,name text,email text,payload jsonb,moderation_status text default 'pending',created_at timestamptz default now());
create table if not exists tips (id bigserial primary key,tip_type text,title text,details text,email text,status text default 'pending',created_at timestamptz default now());
create table if not exists advice_questions (id bigserial primary key,display_name text,anonymous boolean default true,email text,question text not null,category text,relationship_context text,consent_to_publish boolean default false,moderation_status text default 'pending',selected_for_article boolean default false,anonymized_question text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists advertisers (id bigserial primary key,business_name text not null,website_url text,contact_email text not null,created_at timestamptz default now());
create table if not exists ad_packages (id bigserial primary key,name text not null,description text,base_price_cents int not null,duration_label text not null,size text not null,active boolean default true);
create table if not exists ad_campaigns (id bigserial primary key,advertiser_id bigint references advertisers(id),package_id bigint references ad_packages(id),stripe_subscription_id text,ad_size text,duration text,quantity int default 1,placement text,target_category text,headline text,body_copy text,cta_text text,landing_url text,image_url text,status text default 'pending',starts_at timestamptz,ends_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists newsletter_subscribers (id bigserial primary key,email text unique not null,preferences text[],status text default 'active',created_at timestamptz default now());
create table if not exists agent_outputs (id bigserial primary key,agent_name text,output_type text,status text,input_summary text,output_json jsonb,confidence_score numeric(3,2),requires_human_review boolean default true,related_article_id bigint,related_campaign_id bigint,related_question_id bigint,created_at timestamptz default now());
create table if not exists site_settings (id bigserial primary key,publication_name text default 'RougaRoux',tagline text default 'AI-Operated New Orleans Magazine',settings jsonb default '{}'::jsonb);
alter table profiles enable row level security;
create policy "Profiles owner read" on profiles for select using (auth.uid() = id);
